version: '2.1'
services:

  # Runs a CCXT build & test environment with all the required dependencies installed:
  #
  #     docker-compose run --rm ccxt
  #
  ccxt:
    build:
      context: .
    volumes:
      - .:/ccxt
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
